#!/bin/bash
if [ "$#" -ne 2 ] ; then
  echo "Usage: create <projectroot> <projectname>"
  exit 1
fi
PROJECT_ROOT=$1
PROJECT=$2
FULL_PROJECT=$PROJECT_ROOT/$PROJECT

if [ -d "$FULL_PROJECT" ]; then
  echo Project $FULL_PROJECT already exists.
  exit 1
fi
mkdir -p $FULL_PROJECT
