#!/bin/bash
if [ "$#" -ne 2 ] ; then
  echo "Usage: scan <projectroot> <projectname>"
  exit 1
fi
PROJECT_ROOT=$1
PROJECT=$2
FULL_PROJECT=$PROJECT_ROOT/$PROJECT

if [ -d "$FULL_PROJECT" ]; then
  cd $FULL_PROJECT
  bandit -r . > .scan_bandit
  snyk test > .scan_snyk
else
  echo Project $FULL_PROJECT does not exist.
  exit 1
fi
